mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      # "gps_garmin",
      "gps_baro",
      # "ground_truth",
    ]

    initial_state_estimator: "gps_baro" # will be used as the first state estimator
    agl_height_estimator: "" # only slightly filtered height for checking min height (not used in control feedback)
  
  obstacle_bumper:

      enabled: true

      switch_tracker: true
      tracker: "MpcTracker"

      switch_controller: true
      controller: "Se3Controller"

      horizontal:

        min_distance_to_obstacle: 1.2 # [m]

        # when enabled, the min_distance_to_obstacle will increased by the distances
        # needed for stopping given the current system constraints
        derived_from_dynamics: true

      vertical:

        min_distance_to_obstacle: 1.2 # [m]

        # when enabled, the min_distance_to_obstacle will increased by the distances
        # needed for stopping given the current system constraints
        derived_from_dynamics: true

  uav_manager:

    takeoff:

      after_takeoff:
        controller: "Se3Controller"

mrs_uav_trajectory_generation:

  # execution time limiter
  max_time: 0.5 # [s]

  # check and fix the max deviation between the input path and the output trajectory
  # by subsampling the original path with more waypoints
  check_trajectory_deviation:
    max_deviation: 0.20 # [m]

  # allows to neglect waypoints in the original path if the new path
  # does not violate max distance from the original path.
  # This makes for similar but sparser paths, which are easier for the
  # trajectory generator to work with.
  path_straightener:
    enabled: true
    max_deviation: 0.20 # [m]
